language: php

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
    fast_finish: true

    include:
        # Current $required_php_version for WordPress: 5.2.4
        # This theme uses namespaces and autoload
        # and can't run on version < 5.6
        # aliased to a recent 5.6.x version
        - php: "5.6"
        # aliased to a recent 7.0.x version
        - php: "7.0"
        # aliased to a recent 7.2.x version
        - php: "7.2"
          # Use this to prepare your build for testing.
          # e.g. copy database configurations, environment variables, etc.
          # Failures in this section will result in build status 'errored'.
          before_install:
            # disable Xdebug to speed up building process
            - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
            # Install PHP packages.
            - composer install --ansi --prefer-dist --no-suggest
            # Install ESLint shareable config for WordPress.
            # @link https://github.com/WordPress-Coding-Standards/eslint-config-wordpress
            - npm install eslint @wordpress/eslint-plugin
          # Run test script commands.
          # Default is specific to project language.
          # All commands must exit with code 0 on success. Anything else is considered failure.
          script:
            # Run the theme through ESLint.
            - npm run lint
            # WordPress Coding Standards and PHPCompatibility.
            # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
            # @link http://pear.php.net/package/PHP_CodeSniffer/
            # @link https://github.com/PHPCompatibility/PHPCompatibilityWP
            - ./vendor/bin/phpcs

before_script:
  # Install PHP packages.
  - composer install --ansi --prefer-dist --no-suggest
script:
  # Search for PHP syntax errors.
  - ./vendor/bin/parallel-lint --blame --exclude vendor/ .

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
    email:
    - tristan@mintsmm.com